# command to execute to start alacritty
alacritty_start_cmd: 'alacritty'

# effective, user-based alacritty config file path
alacritty_config_file_path: "/home/{{ alacritty_user_name }}/.config/alacritty/alacritty.yml"

# show window borders, and show window title bar
show_window_borders_and_title_bar: true

# padding (in pixels) to put in between terminal text and window border
window_padding_pixels: 5

# Visual bell (screen flash) duration in millisec. Set to 0 to disable bell.
visual_bell_duration_ms: 300

# shape of cursor: 'Block', 'Beam', or 'Underline'
cursor_shape: 'Block'

# whether cursor blinks: 'Never', 'Off', 'On', or 'Always'
cursor_blink: 'Off'

# cursor blink interval in millisec (if cursor_blink sets blinking)
cursor_blink_interval_ms: 750

# when the terminal window is not focused, show a 'hollow box' cursor
show_hollow_cursor_on_unfocus: true

# shell command to start in the terminal emulator
shell_cmd: '/bin/sh'

