# command to execute to start alacritty
alacritty_start_cmd: 'alacritty'

# effective, user-based alacritty config file path
alacritty_config_file_path: "/home/{{ alacritty_user_name }}/.config/alacritty/alacritty.yml"

# the $TERM env var that will be set for each new instance of alacritty
term_env_var: 'alacritty'

# show window borders, and show window title bar
show_window_borders_and_title_bar: false

# background opacity of the terminal window: 0.0 (transparent) to 1.0 (opaque)
# NOTE: requires separate compositor application to be running
window_opacity: 0.9

# padding (in pixels) to put in between terminal text and window border
window_padding_pixels: 5

