# command to execute to start alacritty
alacritty_start_cmd: 'alacritty'

# effective, user-based alacritty config file path
alacritty_config_file_path: "/home/{{ alacritty_user_name }}/.config/alacritty/alacritty.yml"

# show window borders, and show window title bar
show_window_borders_and_title_bar: true

# padding (in pixels) to put in between terminal text and window border
window_padding_pixels: 5

# shell command to start in the terminal emulator
shell_cmd: '/bin/sh'

