# shell command to start in the terminal emulator
alacritty_shell_cmd: '/bin/sh'
# allow live-reload of any config file changes
alacritty_allow_live_config_reload: false

# show window borders, and show window title bar
alacritty_show_window_borders_and_title_bar: true
# padding (in pixels) to put in between terminal text and window border
alacritty_window_padding_pixels: 5

# max number of lines to keep in the scrollback buffer
alacritty_scrollback_history: 10000

# Visual bell (screen flash) duration in millisec. Set to 0 to disable bell.
alacritty_visual_bell_duration_ms: 300
# shape of cursor: 'Block', 'Beam', or 'Underline'
alacritty_cursor_shape: 'Block'
alacritty_cursor_shape_vi_mode: 'Block'
# whether cursor blinks: 'Never', 'Off', 'On', or 'Always'
alacritty_cursor_blink: 'Off'
alacritty_cursor_blink_vi_mode: 'Always'
# cursor blink interval in millisec (if alacritty_cursor_blink sets blinking)
alacritty_cursor_blink_interval_ms: 500
# for cursor_blink 'On', cursor will stop blinking after this number of seconds
alacritty_cursor_blink_timeout_sec: 30
# when the terminal window is not focused, show a 'hollow box' cursor
alacritty_show_hollow_cursor_on_unfocus: true

# temporarily hide the mouse cursor when typing
alacritty_hide_mouse_when_typing: true

# hint characters for URL-open links
alacritty_hint_mode_chars: 'asdfghjkl'
# command to run in hint mode to open a URL
alacritty_hint_mode_open_url_cmd: 'xdg-open'

