- name: "Create user config file directories, if not exist"
  ansible.builtin.file:
    path: "{{ alacritty_config_file_path | dirname }}"
    state: directory
    owner: "{{ alacritty_user_name }}"
    mode: '755'
  become: true
  become_user: root

- name: "Configure all alacritty behavior in '{{ alacritty_config_file_path }}'"
  ansible.builtin.template:
    dest: "{{ alacritty_config_file_path }}"
    src: "alacritty_toml.j2"
    owner: "{{ alacritty_user_name }}"
    mode: '644'
    force: true
  become: true
  become_user: root

